[build]
  base = "frontend"
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://unpkg.com 'sha256-RODCtdmOn6Xt22F1/gyv4+7s1dbZd1UNPir3wtTn4/k=';
      style-src 'self' https://cdn.jsdelivr.net https://fonts.googleapis.com 'unsafe-inline';
      font-src https://fonts.gstatic.com;
      img-src 'self' data:;
      connect-src 'self' https://theidealcareerprogenerator.onrender.com https://theidealcareerprogenerator.netlify.app;
    """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/portfolio.html"
  status = 200

[[redirects]]
  from = "/cv"
  to = "/cv.html"
  status = 200

[[redirects]]
  from = "/coverletter"
  to = "/coverletter.html"
  status = 200
