[build]
  command = ""
  publish = "frontend/"

[[redirects]]
  from = "/feedback-success.html"
  to = "/feedback-success.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
