services:
  - type: web
    name: theidealcareerproGenerator
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://theidealcareerprogenerator.netlify.app
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_KEY
        fromSecret: SUPABASE_KEY
      - key: GH_TOKEN
        fromSecret: GH_TOKEN
      - key: GH_OWNER
        value: Theidealcareerpro
      - key: GH_REPO
        value: e-portfolioGeneratorNEW
