services:
  - type: web
    name: portfolio-generator-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://<your-netlify-domain>.netlify.app
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_KEY
        fromSecret: SUPABASE_KEY
      - key: GITHUB_TOKEN
        fromSecret: GITHUB_TOKEN
      - key: GITHUB_OWNER
        value: <your-github-username>
      - key: GITHUB_REPO
        value: eportfolio-files
