name: Cleanup Expired Portfolios

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch: # Manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cleanup API
        env:
          API_URL: https://<your-render-domain>.onrender.com/api/cleanup
        run: |
          curl -X POST $API_URL
